ALTER TABLE `customer_kmz_shl` CHANGE `is_shirt_cuff` `is_shirt_cuff` TINYINT NOT NULL DEFAULT '0';
 ALTER TABLE `customer_kmz_shl` CHANGE `is_darts` `is_darts` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_sleeve_placket` `is_sleeve_placket` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_front_placket` `is_front_placket` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_button_cuff` `is_button_cuff` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_french_cuff` `is_french_cuff` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_collar` `is_collar` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_moon_neck` `is_moon_neck` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_straight_front` `is_straight_front` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_1side_pocket` `is_1side_pocket` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_2side_pocket` `is_2side_pocket` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_fancy_button` `is_fancy_button` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_covered_fly` `is_covered_fly` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_band` `is_band` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_round_front` `is_round_front` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_front_pocket` `is_front_pocket` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_shalwar_pocket` `is_shalwar_pocket` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_open_sleeves` `is_open_sleeves` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_plain_button` `is_plain_button` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_plane_placket` `is_plane_placket` TINYINT(1) NULL DEFAULT '0',
 CHANGE `is_plain_cuff` `is_plain_cuff` TINYINT(1) NULL DEFAULT '0', 
 CHANGE `is_double_cuff` `is_double_cuff` TINYINT(1) NULL DEFAULT '0', 
 CHANGE `is_design` `is_design` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_kanta` `is_kanta` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_stitch` `is_stitch` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_thread` `is_thread` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_bookrum` `is_bookrum` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_shirt_collar` `is_shirt_collar` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_shirt_collar_type` `is_shirt_collar_type` TINYINT(1) NOT NULL DEFAULT '0';
 
 
 
 
 
 ALTER TABLE `customer_coat_size` CHANGE `is_breasted` `is_breasted` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_button_suit` `is_button_suit` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_lapel` `is_lapel` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_wear` `is_wear` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_vent` `is_vent` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_lined` `is_lined` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_ticket` `is_ticket` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_slant` `is_slant` TINYINT(1) NOT NULL DEFAULT '0', 
 CHANGE `is_button` `is_button` TINYINT(1) NOT NULL DEFAULT '0',
 CHANGE `is_double_breasted` `is_double_breasted` TINYINT(1) NULL DEFAULT '0',
 CHANGE `is_two_button_suit` `is_two_button_suit` TINYINT(1) NULL DEFAULT '0', 
 CHANGE `is_peak_lapel` `is_peak_lapel` TINYINT(1) NULL DEFAULT '0', 
 CHANGE `is_shawl_lapel` `is_shawl_lapel` TINYINT(1) NULL DEFAULT '0',
 CHANGE `is_casual_wear` `is_casual_wear` TINYINT(1) NULL DEFAULT '0', 
 CHANGE `is_groom_wear` `is_groom_wear` TINYINT(1) NULL DEFAULT '0',
 CHANGE `is_double_vent` `is_double_vent` TINYINT(1) NULL DEFAULT '0',
 CHANGE `is_no_vent` `is_no_vent` TINYINT(1) NULL DEFAULT '0',
 CHANGE `is_half_lined` `is_half_lined` TINYINT(1) NULL DEFAULT '0', 
 CHANGE `is_regular` `is_regular` TINYINT(1) NULL DEFAULT '0',
 CHANGE `is_metalic_button` `is_metalic_button` TINYINT(1) NULL DEFAULT '0';